spring.application.name=hello-micro-service 
server.port=5100 
spring.boot.admin.client.url=http://localhost:5599 
logging.level.root=INFO 
logging.pattern.console=%-5level %logger{36} - %m %n 
management.endpoints.web.exposure.include=* 
management.endpoint.scheduledtasks.enabled=false 
management.endpoint.caches.enabled=false 
management.endpoints.web.exposure.exclude=conditions,configprops 
management.endpoint.health.show-details = always 
info.app.name=hello-micro-service 
info.app.description=This is my Hello MicroService 
info.app.version=1.0 
info.app.encoding=UTF-8 
info.app.java.version=16.0.2 
info.app.developer=Srinivas Dande 
info.app.company=Java Learning Center