spring.application.name=MyBootAdminServer
server.port=5599


#management.endpoints.web.exposure.include=info,beans
#management.endpoints.web.exposure.include=health,info,beans
management.endpoints.web.exposure.include=*

management.endpoint.scheduledtasks.enabled=false
management.endpoint.caches.enabled=false

#management.endpoints.web.exposure.exclude=conditions,configprops



management.endpoint.health.show-details = always

info.app.name=MyBootAdminServer
info.app.description=This is MyBootAdminServer 
info.app.version=1.0 
info.app.encoding=UTF-8 
info.app.java.version=16.0.2 
info.app.developer=Rishi Sharma 
info.app.company=HWL Advanced Technology Private Limited