#DataBase Properties
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/myjlcdb5
spring.datasource.username=root
spring.datasource.password=root


#Hikari Properties
#spring.datasource.hikari.maximum-pool-size=100
#spring.datasource.hikari.idle-timeout=20000

#Log Properties
logging.level.root=debug
logging.pattern.console=%-5level%logger{36}-%m%n

